### ISSUE TITLE
从infomation_schema数据库的columns、schemata、tables查询数据报错 

### ISSUE THREAD

**Issue by Knuth1989** [baidu/palo#123]
1）从infomation_schema数据库的columns、schemata、tables查询数据报错
ERROR 1064 (HY000): reopen rpc error, address=TNetworkAddress(
2）be直接Alive 变成false;
2）fe日志中报错
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:1.8.0_131]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_131]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_131]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_131]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_131]
	at java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_131]
	at org.apache.thrift.transport.TSocket.open(TSocket.java:221) ~[libthrift-0.9.3.jar:0.9.3]

**Comment by lingbin** [comment]
这是一个bug，我已经修复提交了，辛苦更新为最新的代码后再试试，详见 #125

**Comment by Knuth1989** [comment]
ok!新版本可以查询了！
