### ISSUE TITLE
http小批量导入失败

### ISSUE THREAD

**Issue by crcc** [baidu/palo#19]
一个fe，一个be，使用预编译的版本palo-0.8.0_20170816_ubuntu16.04_gcc540.tar.gz。按这个教程[https://github.com/baidu/palo/blob/master/docs/user_guide/tutorial.md]()中小批量导入一节执行下面命令

    $ curl --location-trusted -u test@example_cluster:test -T table1_data http://127.0.0.1:8030/api/example_db/table1/_load?label=table1_20170816

返回

    {
	    "status": "Fail",
	    "msg": "Request miniload from master(127.0.1.1:9020) because: No more data to read."
    }

fe的日志如下

2017-08-16 18:02:41,764 ERROR 126 [TThreadPoolServer$WorkerProcess.run():297] Error occurred during processing of message.
java.lang.NullPointerException
	at com.baidu.palo.load.Load.createLoadJob(Load.java:515) ~[palo-fe.jar:?]
	at com.baidu.palo.load.Load.addLoadJob(Load.java:339) ~[palo-fe.jar:?]
	at com.baidu.palo.load.Load.addLoadJob(Load.java:322) ~[palo-fe.jar:?]
	at com.baidu.palo.service.FrontendServiceImpl.miniLoad(FrontendServiceImpl.java:295) ~[palo-fe.jar:?]
	at com.baidu.palo.thrift.FrontendService$Processor$miniLoad.getResult(FrontendService.java:1113) ~[palo-fe.jar:?]
	at com.baidu.palo.thrift.FrontendService$Processor$miniLoad.getResult(FrontendService.java:1098) ~[palo-fe.jar:?]
	at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:39) ~[libthrift-0.9.3.jar:0.9.3]
	at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:39) ~[libthrift-0.9.3.jar:0.9.3]
	at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:286) [libthrift-0.9.3.jar:0.9.3]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_141]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_141]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]

be的日志如下

I0816 18:02:41.753830 10454 mini_load.cpp:472] accept one request HttpRequest:
method:1
uri:/api/example_db/table1/_load
raw_path:/api/example_db/table1/_load
headers:
key=Accept, value=*/*
key=Authorization, value=Basic dGVzdEBleGFtcGxlX2NsdXN0ZXI6dGVzdA==
key=Content-Length, value=65
key=Expect, value=100-continue
key=Host, value=127.0.1.1:8040
key=User-Agent, value=curl/7.52.1
params:
key=db, value=example_db
key=label, value=table1_20170816
key=table, value=table1
I0816 18:02:41.758327 10454 mini_load.cpp:221] Save file to path /home/crc/palo-0.8.0_ubuntu16.04_gcc540/disks/palo.SSD/mini_download/example_db/table1_20170816/table1..20170816180241.755049 success.
W0816 18:02:41.761920 10454 mini_load.cpp:345] Retrying mini load from master(127.0.1.1:9020) because: No more data to read.
W0816 18:02:41.766263 10454 mini_load.cpp:362] Request miniload from master(127.0.1.1:9020) because: No more data to read.
I0816 18:02:41.797876 10454 status.cpp:49] Request miniload from master(127.0.1.1:9020) because: No more data to read.
    @           0xb48300  palo::Status::Status()
    @           0xf995a9  palo::MiniLoadAction::load()
    @           0xf9a5e0  palo::MiniLoadAction::handle()
    @           0xf8346a  palo::Webserver::mongoose_callback()
    @           0xf83bb9  palo::Webserver::mongoose_callback_static()
    @           0xfa4fec  call_user
    @           0xfada54  handle_request
    @           0xfafbf3  process_new_connection
    @           0xfb006d  worker_thread
    @     0x7f2f52fbe493  start_thread
    @     0x7f2f51d0eafe  (unknown)

**Comment by imay** [comment]
可以提供一下show proc '/backends'的信息么？

**Comment by crcc** [comment]
MySQL [(none)]> show proc '/backends'\G
*************************** 1. row ***************************
              Cluster: example_cluster
            BackendId: 10000
                   IP: 127.0.1.1
             HostName: debian
        HeartbeatPort: 9050
               BePort: 9060
             HttpPort: 8040
        LastStartTime: 2017-08-16 17:46:27
        LastHeartbeat: 2017-08-17 08:49:30
                Alive: true
 SystemDecommissioned: false
ClusterDecommissioned: false
            TabletNum: 40
1 row in set (0.01 sec)

刚刚又试了一下，问题依旧，fe和be的日志也基本没变

**Comment by morningman** [comment]
这个应该是因为获取到 127.0.1.1 这个ip，导致我们前后端存储的ip不一致造成的。
这两天我们会提供解决方案。
如果继续测试使用，可能需要临时修改下机器host文件，屏蔽掉127.0.1.1 这个ip
